server:
  port: 8085

spring:
  mongodb:
    uri: ${MONGO_INTEGRATION_URI}
  ai:
    google:
      genai:
        api-key: ${GOOGLE_AI_API_KEY}
        chat:
          model: ${GOOGLE_AI_MODEL}
        embedding:
          api-key: ${GOOGLE_AI_API_KEY}
          text:
            model: ${GOOGLE_EMBEDDING_MODEL}
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    #      properties:
    #        spring.json.add.type.headers: true
    #        spring.json.type.mapping: >
    #          sos_event:iuh.fit.dispatchservice.dtos.response.RescueDetailResponse
    consumer:
      group-id: dispatch-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
         spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
         spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
#         spring.json.use.type.headers: true
         spring.json.trusted.packages: "iuh.fit.common.kafka.dto"
#         spring.json.type.mapping: >
#           sos_event:iuh.fit.dispatchservice.dtos.response.RescueDetailResponse

weather:
  api:
    key: ${WEATHER_API_KEY}
    
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
