server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${NOTIFICATION_DB_NAME:notification_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: update
    show-sql: true
  # kafka:
  #   bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9094}
  #   consumer:
  #     group-id: notification-group
  #     auto-offset-reset: earliest
  #     key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
  #     value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
  #     properties:
  #       spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
  #       spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
  #       spring.json.use.type.headers: true
  #       spring.json.trusted.packages: "iuh.fit.*"
  #       spring.json.type.mapping: >
  #         sos_event:iuh.fit.notificationservice.dtos.RescueDetailResponse

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
