server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs

eureka:
  client:
    service-url:
      # Đăng ký chính Config Server với Eureka
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
